src/Match Game Oficial/Match Game Oficial/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Match_Game_Oficial.Models
{
    [Table("Usuarios")]
    public class Usuario
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Insira o dado corretamente!")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Insira o dado corretamente!")]
        public string Senha { get; set; }

        [EmailAddress]
        [Required(ErrorMessage = "Insira o dado corretamente!")]
        public string Email { get; set; }

        [DataType(DataType.Date)] 
        public DateTime Data_Nascimento { get; set; }

        public byte[]? Foto {  get; set; }

        public string? UsuarioLink { get; set; } 



    }
}

src/Match Game Oficial/Match Game Oficial/Controllers/FavoritosController.cs
using Microsoft.AspNetCore.Mvc;


namespace Match_Game_Oficial.Controllers
{
    public class FavoritosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    
    
    }
}

src/Match Game Oficial/Match Game Oficial/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Match_Game_Oficial.Models;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.CodeAnalysis.Scripting;

namespace Match_Game_Oficial.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly DataContext _context;

        public const string EmailRecomendacao = "email";
        private readonly ILogger<JogosRecomendadosController> _logger;


        public UsuariosController(DataContext context, ILogger<JogosRecomendadosController> logger)
        {
            _context = context;
            _logger = logger;

        }

       
        //Onde Criamos a view Login
        public IActionResult login()
                {
                    return View();
                }


        //Onde implementamos as validações e requisições
        [HttpPost]
        public async Task<IActionResult> login(Usuario usuario)
        {
            var dados = await _context.Usuarios
                .Where(u => u.Email == usuario.Email)
                .FirstOrDefaultAsync();

            if (dados == null)
            {
                ModelState.AddModelError("Email", "O endereço de email não está cadastrado!");

                return View();
            }

            bool senhaOk = BCrypt.Net.BCrypt.Verify(usuario.Senha, dados.Senha);

            if (senhaOk)
            {
                string email = dados.Email;

                HttpContext.Session.SetString(EmailRecomendacao, email);
                Console.WriteLine(dados.Email);
                _logger.LogInformation($"Email na sessão: {email}");

                var claims = new List<Claim>
                {
                new Claim(ClaimTypes.Email, dados.Email),
                new Claim(ClaimTypes.Name, dados.Nome)

                };

                var usuarioIdentity = new ClaimsIdentity(claims, "login");

                ClaimsPrincipal principal = new ClaimsPrincipal(usuarioIdentity);

                var props = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    ExpiresUtc = DateTime.UtcNow.ToLocalTime().AddHours(8),
                    IsPersistent = true,
                };

                await HttpContext.SignInAsync(principal, props);



                return Redirect("/Recomendados/Index");
            }
            else
            {
                ModelState.AddModelError("Email", "Email ou senha incorretos!");

                return View();
            }
        }

        //Quando o usuário apertar em sair vai para 
        public async Task<IActionResult> Logout()
        {
            string email = HttpContext.Session.GetString(EmailRecomendacao);
            Console.WriteLine(email);

            await HttpContext.SignOutAsync();
            return RedirectToAction("Login", "Usuarios");
           

        }


        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Usuarios == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        public FileContentResult getImg(int id)
        {
            byte[] byteArray = _context.Usuarios.Find(id).Foto;
            return byteArray != null
                ? new FileContentResult(byteArray, "image/jpeg")
                : null;
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Senha,Email,Data_Nascimento,Foto")] Usuario usuario, IFormFile file)
        {
            if (EmailJaExiste(usuario.Email))
            {
                ModelState.AddModelError("Email", "Este email já está em uso.");
                return View(usuario);
            }

            if (ModelState.IsValid)
            {
                Console.WriteLine(usuario.Id) ;
                if (file.Headers != null && file.Length > 0)
                {
                   
                    using (var memoryStream = new MemoryStream())
                    {
                        await file.CopyToAsync(target: memoryStream);
                        byte[] data = memoryStream.ToArray();
                        usuario.Foto = memoryStream.ToArray();
                    }
                }

                usuario.Senha = BCrypt.Net.BCrypt.HashPassword(usuario.Senha);
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(login));
            }
            return View(usuario);
        }

        private bool EmailJaExiste(string email)
        {
            return _context.Usuarios.Any(u => u.Email == email);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Usuarios == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Senha,Email,Data_Nascimento,Foto")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Usuarios == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Usuarios == null)
            {
                return Problem("Entity set 'DataContext.Usuarios'  is null.");
            }
            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuarios.Remove(usuario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
          return (_context.Usuarios?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

src/Match Game Oficial/Match Game Oficial/Views/Usuarios/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Match Game</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navBar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Match_Game.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="logo" src="/img/logo.png" />
                </a>
                <button class="navbar-toggler pe-4" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 d-flex justify-content-end pe-5 pt-2">
                        <li class="nav-item">
                            <img class="navIcon" src="/img/para-voce.png" />
                            <a class="nav-link text-light" asp-area="" asp-controller="Jogos" asp-action="ListarJogos">Para Você</a>
                        </li>
                        <li class="nav-item">
                            <img class="navIcon-fav" src="/img/favoritos.png" />
                            <a class="nav-link text-light" asp-area="" asp-controller="Favoritos" asp-action="Index">Favoritos</a>
                        </li>
                        <li class="nav-item">
                            <img class="navIcon-perfil" src="/img/perfil.png" />
                            <a id="perfil" class="nav-link text-light" asp-area="" asp-controller="Usuarios" asp-action="Login">Perfil</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <!--
                            <li class="nav-item">Olá, @User.Identity.Name <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a></li>
                            -->


                            <li class="nav-item logout " style="font-family: 'Jost';color: #ffff; margin-left: -34%; margin-top: 7%;">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">
                                    <img class="navSair pe-5 " style="width: 85px;" src="~/img/logout (2).png"></img>
                                    <span class="NavSair me-0 ms-1" style="margin-top: -7%; cursor: pointer; display:flex; flex-direction: column; font-family: 'Jost';color: #ffff;">Sair</span>
                                </a>
                                
                                
                                
                            </li>
                        }
                        else
                        {   <!--
                            <li class="nav-item"> <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a></li>
                            -->
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p>&copy; 2023 - Match Game</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>