src/Match Game Oficial/Match Game Oficial/Models/Recomendado.cs
using System.ComponentModel.DataAnnotations;

namespace Match_Game_Oficial.Models
{
    public class Recomendado
    {

        [Required]
        [Display(Name = "A partir de qual ano você tem interesse?")]
        public int AnoInicial { get; set; }

        [Required]
        [Display(Name = "Até qual ano você tem interesse?")]
        public int AnoFinal { get; set; }

        [Required]
        [Display(Name = "Selecione a plataforma de interesse")]
        public Form_Plat Plataforma { get; set; }

        [Required]
        [Display(Name = "Selecione o gênero de interesse")]
        public Form_Gen Genero { get; set; }
    }

    public enum Form_Plat
    {
        IOS = 4,
        Playstations = 2,
        Xbox = 3,
        Computador = 1,
        Android = 8,
        Linux = 6,
        Nintendo = 7,
        Atari = 9,
        Comodore = 10,
        Sega = 11,
        Web = 14,
    }

    public enum Form_Gen
    {
        Ação = 1,
        Indie = 2,
        Aventura = 3,
        Rpg = 4,
        Estratégia = 5,
        Shooter = 6,
        Casual = 7,
        Simulação = 8,
        Puzzle = 9,
        Arcade = 10,
        Plataformer = 11,
        Multiplayer = 12,
        Race = 13,
        Sports = 14,
        Fight = 15,
        Family = 16,
        BoardGames = 17,
        Educational = 18,
        Card = 19
    }

}

src/Match Game Oficial/Match Game Oficial/Controllers/RecomendadosController.cs
using Match_Game_Oficial.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Match_Game_Oficial.Controllers
{
    public class RecomendadosController : Controller
    {
        private readonly DataContext _context;
        public const string EmailRecomendacao = "email";


        public RecomendadosController(DataContext context)
        {

            _context = context;
        }

        // Dicionários para mapear valores dos enums para os valores desejados
        private static readonly Dictionary<Form_Gen, string> GeneroMapping = new Dictionary<Form_Gen, string>
        {
            { Form_Gen.Ação, "1" },
            { Form_Gen.Indie, "2" },
            { Form_Gen.Aventura, "3" },
            { Form_Gen.Rpg, "4" },
            { Form_Gen.Estratégia, "5" },
            { Form_Gen.Shooter, "6" },
            { Form_Gen.Casual, "7" },
            { Form_Gen.Simulação, "8" },
            { Form_Gen.Puzzle, "9" },
            { Form_Gen.Arcade, "10" },
            { Form_Gen.Plataformer, "11" },
            { Form_Gen.Multiplayer, "12" },
            { Form_Gen.Race, "13" },
            { Form_Gen.Sports, "14" },
            { Form_Gen.Fight, "15" },
            { Form_Gen.Family, "16" },
            { Form_Gen.BoardGames, "17" },
            { Form_Gen.Educational, "18" },
            { Form_Gen.Card, "19" }
        };

        private static readonly Dictionary<Form_Plat, string> PlataformaMapping = new Dictionary<Form_Plat, string>
        {
            { Form_Plat.IOS, "4" },
            { Form_Plat.Playstations, "2" },
            { Form_Plat.Xbox, "3" },
            { Form_Plat.Computador, "1" },
            { Form_Plat.Android, "8" },
            { Form_Plat.Linux, "6" },
            { Form_Plat.Nintendo, "7" },
            { Form_Plat.Atari, "9" },
            { Form_Plat.Comodore, "10" },
            { Form_Plat.Sega, "11" },
            { Form_Plat.Web, "14" }
        };

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Recomendado model)

        {
            string email = HttpContext.Session.GetString(EmailRecomendacao);

            if (ModelState.IsValid)
            {
                // Obter os valores necessários do modelo
                var anoInicial = Convert.ToInt32(model.AnoInicial);
                var anoFinal = Convert.ToInt32( model.AnoFinal);
                var plataforma = model.Plataforma;
                var genero = model.Genero;

                Console.WriteLine(anoFinal);
                Console.WriteLine(anoInicial);


                if (anoFinal >= anoInicial && anoInicial < 2024 && anoFinal < 2024 )
                {
                    Console.WriteLine("Ano Correto");


                    // Verificar se os valores estão nos dicionários
                    if (GeneroMapping.TryGetValue(genero, out var generoMapeado) && PlataformaMapping.TryGetValue(plataforma, out var plataformaMapeada))
                    {
                        // Construir a URL da API com base nos valores do modelo
                        var apiUrl = $"https://api.rawg.io/api/games?key=69f74f8a6cde46529c5d0923786cdab7&parents_platforms={plataformaMapeada}&genres={generoMapeado}&dates={anoInicial}-01-01,{anoFinal}-06-01";

                        var dados = await BuscarInfo(email);
                        Console.WriteLine(apiUrl);
                        Console.WriteLine(email);

                        if (dados.Count > 0)
                        {
                            var primeiroUser = dados[0];


                            primeiroUser.UsuarioLink = apiUrl;

                            _context.Usuarios.Update(primeiroUser);
                            _context.SaveChanges();

                        }

                        // Executar um script JavaScript para salvar no localStorage
                        ViewData["Script"] = $"<script>alert('Seus dados foram enviados!'); window.location.href='/JogosRecomendados';</script>";

                        // Retornar para a mesma view
                        return RedirectToAction("Index", "JogosRecomendados");
                    }
                }
                else 
                {
                    /*
                    ModelState.AddModelError("Valida", "O Ano Inicial deve ser menor ou igual ao ano Final, não ultrapassando 2024!");
                    */

                    ViewBag.Message = "O Ano Inicial deve ser menor ou igual ao ano Final, não ultrapassando 2024!";

                    /*
                    ViewData["Script"] = $"<script>alert('O ano inicial ou final não é válido!');</script>";
                    */

                    Console.WriteLine("Ano incorreto");
                    return View(model);
                }
            }

            // Se o modelo não for válido, retorne para a view com os erros de validação.
            return View(model);
        }

        public async Task<List<Usuario>> BuscarInfo(string email)
        {
            var usuarios = await _context.Usuarios
                .Where(u => u.Email == email)
                .ToListAsync();

            return usuarios;
        }

    }
}

src/Match Game Oficial/Match Game Oficial/Views/Recomendados/Index.cshtml
<link rel="stylesheet" href="~/css/login.css" asp-append-version="true" />

@model Match_Game_Oficial.Models.Recomendado



<!-- @Html.Raw(ViewData["Script"]) -->
@if (ViewBag.Message != null)
{
    <div class="alert alert-danger" style="text-align: center;" role="alert">
        @ViewBag.Message
    </div>
}


<main class="main-cadastro">

    <h1 style="font-size:1.8em;">QUAL TIPO DE JOGO  VOCÊ CURTE?</h1>
    <p>Preencha os dados abaixo para obter uma lista personalizada com o seu gosto! </p>

    <p></p>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Index" asp-controller="Recomendados" method="post">
                @Html.AntiForgeryToken()

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="AnoInicial" class="control-label">Ano Inicial<span style="color: #FF0000">*</span></label>
                    <input asp-for="AnoInicial" class="form-control" />
                    <span asp-validation-for="AnoInicial" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="AnoFinal" class="control-label">Ano Final<span style="color: #FF0000">*</span></label>
                    <input asp-for="AnoFinal" class="form-control" />
                    <span asp-validation-for="AnoFinal" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Plataforma" class="control-label">Plataforma<span style="color: #FF0000">*</span></label>
                    <select asp-for="Plataforma" asp-items="Html.GetEnumSelectList<Form_Plat>()" class="form-control"></select>
                    <span asp-validation-for="Plataforma" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Genero" class="control-label">Gênero<span style="color: #FF0000">*</span></label>
                    <select asp-for="Genero" asp-items="Html.GetEnumSelectList<Form_Gen>()" class="form-control"></select>
                    <span asp-validation-for="Genero" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
    </div>

</main>